name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Akmalwizdom
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          filename: github-metrics.svg
          
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Akmalwizdom
          template: classic
          base: ""
          filename: languages.svg
          plugin_languages: yes
          plugin_languages_ignored: ""           # Clear ignores to see if anything shows up
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes          # Deeper analysis
          plugin_languages_categories: programming
          plugin_languages_limit: 8
          output_action: commit
          committer_branch: output
          committer_message: "chore: update languages metrics"
          
      - name: GitHub Streak and Activity Graph
        run: |
          mkdir -p dist
          curl -o dist/streak.svg "https://nirzak-streak-stats.vercel.app/?user=Akmalwizdom&theme=tokyonight&hide_border=false"
          curl -o dist/graph.svg "https://github-readme-activity-graph.vercel.app/graph?username=Akmalwizdom&theme=one-dark&area=true&hide_border=false"
          
      - name: Push Streak to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
